# 공동 3위의 승수를 계산해서 그 이상인 팀 전부를 부르는 쿼리
SELECT TEAM, WIN 
FROM SQL_3
WHERE WIN >= (SELECT DISTINCT WIN FROM SQL_3 
ORDER BY WIN DESC LIMIT 2,1)
ORDER BY WIN DESC;

SELECT EMP.A, EMP.B, EMP.C, DEPT.D, DEPT.E
FROM EMP
LEFT JOIN DEPT ON EMP.C = DEPT.C;

SELECT EMP.A, EMP.B, EMP.C, DEPT.D, DEPT.E
FROM EMP
RIGHT JOIN DEPT ON EMP.C = DEPT.C;

# OUTER JOIN (FULL OUTER JOIN)
SELECT EMP.A, EMP.B, EMP.C, DEPT.D, DEPT.E
FROM EMP
LEFT JOIN DEPT ON EMP.C = DEPT.C
UNION
SELECT EMP.A, EMP.B, EMP.C, DEPT.D, DEPT.E
FROM EMP
RIGHT JOIN DEPT ON EMP.C = DEPT.C;